---
apiVersion: v1
kind: ReplicationController

metadata:
  name: app
spec:
  replicas: 2
  selector:
    name: app

  template:
    metadata:
      name: app
      labels:
        name: app

    spec:
      containers:
      - name: app
        resources:
          requests:
            cpu: 200m
        env:
          - name: RACK_ENV
            value: production
        image: aespinosa/stress
        ports:
          - containerPort: 9292
