---
apiVersion: v1
kind: ReplicationController

metadata:
  name: app
spec:
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        name: app

    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: application
      containers:
      - name: app
        resources:
          requests:
            cpu: 1000m
        image: aespinosa/stress
