---
apiVersion: v1
kind: ReplicationController

metadata:
  name: app
spec:
  replicas: 70
  template:
    metadata:
      name: app
      labels:
        name: app

    spec:
      containers:
      - name: app
        resources:
          requests:
            cpu: 1000m
        env:
          - name: RACK_ENV
            value: production
        image: aespinosa/stress
        ports:
          - containerPort: 9292
